# TODO: 补充docker compose配置文件
version: '3.8'

services:
  app:
    build: .
    container_name: app
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: thss
      MYSQL_USER: root
      MYSQL_PASSWORD: 2022012110
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate --settings=app.settings_prod 
        python manage.py init_db --settings=app.settings_prod 
        DJANGO_SETTINGS_MODULE=app.settings_prod gunicorn -w4 -b 0.0.0.0:8000 --log-level=debug app.wsgi
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - nginx_net
      - mysql_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - nginx_net

  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2022012110
      MYSQL_DATABASE: thss
      TZ: Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']  
    volumes:
      - /home/ubuntu/mysql/:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mysql_net

networks:
  nginx_net:
    driver: bridge
  mysql_net:
    driver: bridge
