# Generated by Django 4.2.5 on 2024-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('nickname', models.CharField(max_length=255, verbose_name='用户名称')),
                ('mobile', models.CharField(max_length=255, verbose_name='手机号')),
                ('magic_number', models.IntegerField(verbose_name='幸运数字')),
                ('url', models.CharField(max_length=255, verbose_name='个人地址')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
